error: 'HTTPSConnectionPool(host=''api.github.com'', port=443): Max retries exceeded
  with url: /search/repositories?q=%28LLM+OR+%22large+language+model%22+OR+genai%29+created%3A%3E2025-10-09&sort=stars&order=desc&per_page=20
  (Caused by NewConnectionError(''<urllib3.connection.HTTPSConnection object at 0xXXXX>:
  Failed to establish a new connection: [Errno 101] Network is unreachable''))'
generated_at: '2025-10-16T22:09:42Z'
items: []
